Repository G3C1/Oasis-Android, pull requests merged in 2022-12, with the labels that each got.

#58 🔀 :: (#57) - 앱 아이콘 변경
  .idea/misc.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/g3c1/oasis_android/di/module/NetworkModule.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#61 🔀 :: Splash 제거
  app/src/main/java/com/g3c1/oasis_android/MainActivity.kt
Labels: bug

#65 🔀 :: (#64) - locate seat position
  app/src/main/java/com/g3c1/oasis_android/feature_seat/data/dto/SeatDTO.kt
  app/src/main/java/com/g3c1/oasis_android/feature_seat/presentation/SeatActivity.kt
  app/src/main/java/com/g3c1/oasis_android/feature_seat/presentation/seatlist/SeatListScreen.kt
  app/src/main/java/com/g3c1/oasis_android/remote/api/FoodApi.kt
  app/src/main/java/com/g3c1/oasis_android/remote/api/PurchaseApi.kt
  app/src/main/java/com/g3c1/oasis_android/remote/api/SeatApi.kt
  app/src/main/java/com/g3c1/oasis_android/remote/api/StoreApi.kt
Labels: enhancement

#67 🔀 :: (#62) - when click fast twice back button terminate app process
  .idea/gradle.xml
  app/src/main/java/com/g3c1/oasis_android/feature_chat/presentation/ChatActivity.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/MenuActivity.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/menu/MenuScreen.kt
  app/src/main/java/com/g3c1/oasis_android/feature_select_store/presentation/scanpage/StoreSelectActivity.kt
Labels: enhancement

#70 🔀 :: (#68)gradle kts로 변경
  build.gradle
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  settings.gradle.kts
Labels: documentation
