Repository G3C1/Oasis-Android, pull requests merged in 2023-05, with the labels that each got.

#85 🔀 :: (#83) - 디테일 페이지 가격 텍스트 밀리는 이슈 해결
  .idea/gradle.xml
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/detail/FoodDetailScreen.kt
  app/src/main/java/com/g3c1/oasis_android/ui/theme/Font.kt
Labels: bug, enhancement

#86 🔀 :: (#84) - 메뉴 디테일 페이지 버튼 수정
  app/src/main/java/com/g3c1/oasis_android/di/module/NetworkModule.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/shopping_basket/component/ShoppingBasketButton.kt
Labels: bug

#88 🔀 :: (#87) - 디테일 페이지 수량 부분 디자인에 맞게 수정
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/detail/FoodDetailScreen.kt
  app/src/main/res/drawable/minus_btn_ic.xml
  app/src/main/res/drawable/plus_btn_ic.xml
Labels: enhancement

#91 🔀 :: (#90) - setting local properties
  .github/workflows/android.yml
  app/build.gradle.kts
  app/src/main/java/com/g3c1/oasis_android/di/module/FakeUrl.kt
  app/src/main/java/com/g3c1/oasis_android/di/module/NetworkModule.kt
Labels: enhancement

#92 🔀 (#63) - modify when click back button path
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/detail/FoodDetailScreen.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/menu/MenuScreen.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/menu/navigation/MenuNavigation.kt
  app/src/main/java/com/g3c1/oasis_android/feature_menu/presentation/shopping_basket/BottomSheet.kt
Labels: enhancement
